### PR TITLE
Windows 10 jumplist error

### PR DESCRIPTION
**Pull request by rekby**
http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=commitdiff;h=8bf5c1b31f1a1449d694e3604e293b0831eb2657#patch1

### CODE REVIEW

**Comment by jbjonesjr** [comment]
:+1:

**Comment by jbjonesjr** [comment]
@rekby can you also propose this PR against @jdantzler's 0.65 fork?

**Comment by rekby** [comment]
Yes, I done.

**Comment by jdantzler** [comment]
I merged the changes for the windows 10 jumplist error on my fork.

**Comment by rekby** [comment]
@jdantzler can you public release with compiled version of putty and other utilities for ease download binary?

**Comment by jdantzler** [comment]
@rekby The compiled versions of putty and the other utilities can be found in the executables folder on my github page.

**Pull request merged**
