### PR TITLE
PuTTY CAC 0.68 Update 1

### PR DESCRIPTION
**Pull request by NoMoreFood**
This release integrates the upstream release of PuTTY 0.68 (by Simon Tatham and other contributors) with the PuTTY CAC modifications authored by Daniel Risacher and later enhanced by Joshua Dantzler.

More information can be found here: https://github.com/NoMoreFood/putty-cac/releases/tag/0.68u1

### CODE REVIEW

**Comment by jdantzler** [comment]
Great work! Thanks for taking the time to sync the changes to the latest version. I will test it out when I get a chance.

**Comment by k3it** [comment]
Very nice work. I see two small problems compared to 0.67.

- When putty attempts to auth via CAPI (with or w/o the agent) the Pin prompt pops up but no place to enter the pin

image

- pageant crashes if I try to remove the CAPI key from the list

image

**Comment by jdantzler** [comment]
@k3it The latest update @NoMoreFood posted should fix trying to remove a CAPI cert from the list.  I'm not sure about the the pin issue you are having though. The pin window comes up fine on my end.  I do see 2 other issues though.

1) Auto loading a CAPI key no longer works
2) Getting random errors about pageant not answering challenge correctly: https://github.com/risacher/putty-cac/issues/27

Hopefully, @NoMoreFood can look into all these issues when he has a chance.  I don't have much time to do so at the moment, but when and if I do I will look into them if they are not resolved.

**Comment by NoMoreFood** [comment]
@k3it.  What operating system are you running?  Nothing really changed in terms of how the dialog is displayed source-code wise, so it could be something with how I compiled it.

@jdantzler I'm not familiar with this functionality of auto-loading the CAPI key.  How does one autoload a CAPI key?  Like from command line?  Prior to seeing your comment, I actually had to created a private test version to autoload *all* eligible keys via a menu option --- maybe I had missed the code change and the functionality was already there!  If interested, you can check it out at the link below.  This also has a potential fix for #27 if you are willing to see if it addressed your particular issue.  Would be interested in your feedback.  Thanks!

https://www.bryanberns.com/files/other/putty-src-.068-cac-dev.7z

**Comment by jdantzler** [comment]
@NoMoreFood Auto-loading of CAPI key(s) was done by creating a shortcut to pageant and editing the target field in the application properties like this:  
"C:\Users\User\Desktop\pageant.exe" CAPI:User\MY\KEY
Then, anytime the pageant shortcut was executed the CAPI keys were auto-loaded.  I  just add the pageant shortcut to the startup folder so it launches with Windows with the CAPI key(s) loaded.

The version you have linked below does auto-load 2 of 3 keys on my machine. Not sure why the third one is not loaded. I like the auto-load checkbox menu option better then the way mentioned above.  It is easier for the end user to use.

I am still getting the pageant not answering challenge error in this version as well.  I believe the issue is related to the putty application. I get the error regardless if I use pageant or putty to authenticate.  When using putty to authenticate I check the box: Attempt "CAPI" Certificate" (Key-only) auth (SSH-2) 
 on the SSH->CAPI tab and have my CAPI cert loaded.  When using pageant I make sure that box is unchecked or I open up one of my saved session under the pageant menu options.  Either way most every time I get the error still.

Thanks!

**Comment by NoMoreFood** [comment]
@jdantzler Thanks for the information.  I will debug those shortly.   Guessing the first one will be easy to figure out.  For the second problem, do you get that message before the PIN prompt?  If so, any chance you could email me your public key certs and the key config file on the destination system?  In either case, the PuTTY log with high verbosity could be helpful.  I worry that if it's a hit-and-miss that it could be related to variable initialization (i.e. random value in memory) and that could be tough to troubleshoot.   Thanks for your cooperation.

**Comment by NoMoreFood** [comment]
@jdantzler If you download from that link again, I believe the command line parameter loading option should be addressed.  Also please let me know if you continue to see the other issues.  I think I know what autoloading the 2 out of 3 certificate issue is as well, but I haven't fixed it yet.  I think the CertFindCertificateInStore API doesn't recognize a certificate with "<All>" intended purposes as a valid client authentication certificate whereas the GUI CertSelectCertificate does.

**Comment by NoMoreFood** [comment]
@jdantzler Autoloading fix is now in as well.

**Comment by k3it** [comment]
> What operating system are you running? Nothing really changed in terms of how the dialog is displayed source-code wise, so it could be something with how I compiled it.

I'm running windows 7.  I've tried this on a different machine with the ActivClient and could not even load the certificates.  The "Select Certificate for CAPI" dialog pops up but hangs without showing available certs.  On a machine with  the plain MS Certificate provider (no activClient) the pin prompt is missing as in the pic above. I've tried to enter the pin 'blind' just in case the input window outside of the dialog boundary but it's not taking it (the OK button stays grey).    

the crash on CAPI cert removal is fixed for me as well.  but can't test the other features yet because of the pin issue.

**Comment by NoMoreFood** [comment]
@k3it Thanks for testing!  I suspect this is something related to library loading and/or the Visual Studio build.   I'm standing up a Windows 7 machine to test.  In the meantime, I'd appreciate you seeing if the 32-bit or 64-bit executables at the following link helps:

https://www.bryanberns.com/files/other/putty-src-.068-cac-with-win7-buildparams.7z

**Comment by NoMoreFood** [comment]
@k3it I tested the version I had released in GitHub and the two links I provided above and both versions linked above on Windows 7 64-Bit.  All of them worked for both certificate enumeration and PIN entry.  I'll try to get ahold of ActivClient to see if that's somehow related.  Just trying to think out of the box... do you happen to use any application/device control software that could be restricting this new executable from talking to hardware?

**Comment by NoMoreFood** [comment]
@k3it No need to test. I was able to reproduce the issue on a fully patched Windows 7 system.  I am investigating now.

**Comment by jdantzler** [comment]
@NoMoreFood I get the message after the PIN prompt.  I'll try to get a log to you shortly.  It seems to start happening normally after the Attempt "CAPI Certificate" (Key-only) auth (SSH-2) box is checked.  The command line parameter loading option seems to be working great now as well as the autoloading feature.  It shows all 3 certs now.  I've been testing on a Windows 10 box so that may be why I didn't see the pin issue you both are seeing on Windows 7 now.

**Comment by NoMoreFood** [comment]
@k3it I updated the code at the earlier link so it includes the fix for Windows 7.  It was not a build issue; the issue was caused by some code that had been added to the upstream 0.68 to prevent DLL hijacking.  There appears to be a bug in the Windows 7 implementation of SetDllDirectory that, when called, prevents the proper instantiation of the certificate / smart card dialog boxes.  I could not find a workaround other than to skip calling SetDllDirectory (just for Windows 7).  If you could test again, I'd appreciate it.

@jdantzler I also found an issue with an uninitialized variable that was definitely causing erratic behavior for me in debug mode.  I doubt it's related to your issue, but it might not hurt to test.  I haven't focused on your remaining issue yet which I will do tonight.

**Comment by k3it** [comment]
> skip calling SetDllDirectory (just for Windows 7)

that fixed the pin prompt problem for me.  The ActivClient cert enumeration now works also.  I do not see any more issues and will let you know if I run into anything.  

appreciate the time you put in to make 0.68 work with the smart cards.

**Comment by jdantzler** [comment]
@NoMoreFood I still have the issue with the latest build you posted.  I sent a putty.log file to your email on file.  Hopefully, it can help some.  Thanks.

**Comment by NoMoreFood** [comment]
For anyone with new issues for this release, please report them here: 

https://github.com/NoMoreFood/putty-cac/issues

**Pull request merged**
